version: '3'
services:
  db:
    image: postgres:13
    container_name: postgres-web
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: django
    build:
      context: .
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/data/static:ro
    depends_on:
      - backend
    ports:
      - "8000:80"
  load_postgres:
    container_name: sqlite_to_postgres
    build:
      context: ./sqlite_to_postgres
    depends_on:
      - nginx
      - backend
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data
    depends_on:
      - load_postgres
    ports:
      - "9200:9200"
  etl:
    container_name: etl
    build:
      context: ./postgres_to_es
    depends_on:
      - elasticsearch
      - load_postgres

volumes:
  postgres_data:
  static_volume:
  elasticsearch_data: